# Generated by Django 3.0.4 on 2020-03-06 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino_finder', '0002_casino_loaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casino',
            old_name='loaction',
            new_name='location',
        ),
    ]
